# Generated by Django 4.1.4 on 2023-01-20 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_store_image_store_rating_bookstore'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeproduct',
            name='image',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
